### ISSUE TITLE
Licence needed

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#11]
This needs a licence. 
There is no chance it could be promoted to part of the main distribution without a compatible licence. see https://github.com/racket/racket/issues/1570

**Comment by Metaxal** [comment]
Actually there is currently a licence at the bottom of the docs: 
https://github.com/Metaxal/script-plugin/blob/master/scribblings/script-plugin.scrbl#L350

But I'm completely fine with converting it to MIT/Apache2 licence.

**Comment by spdegabrielle** [comment]
thanks

**Comment by spdegabrielle** [comment]
Sorry didn’t have Apache licence 2 to hand

**Comment by Metaxal** [comment]
That should be fine as the MIT license is very non limiting.
