### ISSUE TITLE
command palette

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#12]
give script-plugin a 'command palette' interaction like other IDE's
https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette

1. command-shift-p
2. search box appears
3. user types 'p'
4. list of options appear: 
    [p                    ]
    **p**asterack
    go to **p**revious line number
    **p**ush
    **p**ull --rebase
5. user quits(esc?), uses arrow keys (then enter) or mouse(click) to select an option or types more letters to reduce the choice.

**Comment by Metaxal** [comment]
Sounds interesting :)
Are you thinking about listing all available keyboard shortcuts and/or menu entries?

**Comment by spdegabrielle** [comment]
yes, triggered by a key combination to allow quick access even if you cant remember the keyboard shortcut, or if one isn't set.
I'll try code something up.

**Comment by Metaxal** [comment]
Implemented in quickscript-extra
