### ISSUE TITLE
Licence MIT missing from menu

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#15]
Sorry a little weird - I can see the script, but it doesn't appear in the menu,

![screen shot 2017-11-28 at 00 09 04](https://user-images.githubusercontent.com/108047/33295935-76f2d682-d3d0-11e7-8938-17f4f7617255.png)

**Comment by spdegabrielle** [comment]
Weird -this only seems to affect MacOS.  It is fine on Windows8

**Comment by spdegabrielle** [comment]
I just notices it has WTPFL and it should be WTFPL 
License: WTFPL - http://www.wtfpl.net I'll do a PR

**Comment by Metaxal** [comment]
For both problems (typo and no MIT), it's likely because you have an old version of the script (the typo was fixed a while ago).
Try to re-import the new script with "Scripts > Manage scritpts > Import bundled script..." and choose author-date.rkt

**Comment by spdegabrielle** [comment]
Thanks - my apologies - I should read the documentation. 
(I’m testing on multiple machines)

**Comment by Metaxal** [comment]
no worries, it's not like it's entirely intuitive
