### ISSUE TITLE
Create github api scripts

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#18]
The tweet script got me thinking about this.
I might see if I can recruit someone to do this...

**Comment by spdegabrielle** [comment]
I wonder if there are other services that would be useful for developers (unlike twitter, which is a fun demo, but more of a hinderance to getting work done...)

**Comment by Metaxal** [comment]
Sounds good :)

**Comment by Metaxal** [comment]
closing since script-plugin is superseded by quickscript
