### ISSUE TITLE
Provided by script opens blank

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#20]
![screen shot 2017-12-11 at 08 17 42](https://user-images.githubusercontent.com/108047/33821754-fb04d4c6-de4c-11e7-92de-4b68d426ebda.png)

**Comment by Metaxal** [comment]
To use this script, you must first place the cursor on a keyword before clicking on "Provided by". Is that what you did?

**Comment by spdegabrielle** [comment]
Thanks - I get it now.
