### ISSUE TITLE
need a (require plot) script

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#21]
it would just look cool and be a great demo.

**Comment by spdegabrielle** [comment]
`
#lang racket/base
(require plot)
; Sample identity function:
;; string? -> (or/c string? #f)
(provide item-callback)
(define (item-callback str) str)

;; See the manual in the Script/Help menu for more information.
(plot (points (build-list 20 (λ _ (list (random) (random))))))
`

**Comment by Metaxal** [comment]
Not sure what you want to achieve here.

Though on a similar idea, I have a script that write slideshow pictures in the editor. Pretty :) (I can share it when I'm home)

**Comment by spdegabrielle** [comment]
Is a task for me. I should have noted that.
Plot is pretty too! I want to do a plot of a sequence datatype. 
Please do share the slideshow pics script.

**Comment by Metaxal** [comment]
Indeed plot is really cool, but do you intend it to be a snippet so as to easily start a new plot?

Here's the slideshow script. (As you can see, I didn't share the rktd file, I think there should be only one file to make it easier to share).

```
#lang racket/base
;;; Laurent Orseau <laurent orseau gmail com> -- 2012-04-21

(require racket/class 
         slideshow
         racket/gui/base)

(define (pict->snip pic)
  (make-object image-snip% (pict->bitmap pic)))
 
(define (at pic x y)
  (vc-append (blank x) (hc-append (blank y) pic)))

(provide item-callback)
(define (item-callback str #:editor ed)
  (define pic (hc-append (colorize (filled-rectangle 10 10) "blue")
                         (colorize (disk 20) "green")
                         (colorize (filled-rectangle 10 30) "red")))
  (send ed insert (pict->snip pic))
  #f)
```

**Comment by spdegabrielle** [comment]
Thanks, No I was intending to select an identifier, and plot the value if it was a sequence, and a scatterplot if it was a sequence of pairs.

Agreed about the single file - did you have an idea of how to do it with submodules?
