### ISSUE TITLE
Single file scripts

### ISSUE THREAD

**Issue by Metaxal** [Metaxal/script-plugin#22]
@spdegabrielle What do you think of the following syntax for a script:
```
#lang racket/base
(require quickscript/utils)

(define-script my-script1
  ([name "My Script 1"]                      ; name in the menu. This is the only mandatory value.
   [path ("Scripts" "Misc")]                 ; Path in the menu. May be outside of the Script menu.
   [help-string "A fantastic script"]        ; some help string that may be useful somewhere
   ....)                                     ; Other properties, to be specified only if not default value
  (λ(str #:frame fr #:editor ed #:file f)    ; the callback where, as currently, not all keywords need to be included
    "Insert me in place of the selection"))  ; string or #f, as currently
```

**Comment by spdegabrielle** [comment]
Looks good. I like the named parameters - they make their purpose instantly clear for new or occasional users.
I would suggest menu-path instead of path, as a future version might need [file]path, but I don’t thing it is a big deal.

**Comment by Metaxal** [comment]
Good idea, let's go with menu-path, which makes it clear what kind of path this is.

**Comment by Metaxal** [comment]
(now using `label` instead of `name`)
We could also use keywords instead of a list of bindings:
```
(define-script my-script1
  #:label "my-label"
  #:menu-path '("submenu" "subsubmenu")
  #:help-string "A fantastic script"
  (λ(str #:frame fr #:editor ed #:file f)
    "Insert me in place of the selection"))
```
It's only 2 characters less in total, so not a big deal, but maybe the syntax coloring of DrRacket makes it more readable. It also makes it clearer that label, menu-path and so on are special names. I'm not sure if there is any downside to this. 
What do you think?

**Comment by Metaxal** [comment]
This would also allow to use the #:persistent keyword without rhs value, i.e., the presence of this keyword means the script is persistent.

**Comment by spdegabrielle** [comment]
I like it!

**Comment by Metaxal** [comment]
Ok, I finished porting everything to one file scripts. It works pretty well and looks clean.

You can test it by install the package the following way:
```
raco pkg install https://github.com/Metaxal/script-plugin.git#one-file-scripts
```
However, it will most likely conflict with your current installation. So either:
- remove you current installation of the script plugin AND remove all you scripts in the user-scripts directory (as these will not be overwritten), and then install with the above command line, or
- create a completely new user, and install a fresh DrRacket and script plugin with the above command line.

I also updated the docs.

I think we should split between the package into 2: the core plugin (package quickscript) and the additional scripts (package quickscript-extra). 

I'm still unsure about how to deal with bundled scripts. The main problem I see is that the user should be able to easily modify a bundled script, in particular to change the keyboard shortcut which may conflict with his/her own user-defined shortcuts.
But a script that is modified by the user cannot be easily overwritten when a new version is available.
(Possibility: keep the bundled scripts in a separate directory where they will be overwritten if updated, but give the user the possibility to "import a bundled script" into his/her own user-scripts directory where scripts in this directory takes precedence over bundled scripts if they have the same name. Scripts in the user directory do not get overwritten).

And merry Christmas!

**Comment by Metaxal** [comment]
You can also rename your user-script directory to something else instead of
deleting it, of course.
Then uninstall the script plugin and reinstall it with the above command.
This will recreate the user-scripts directory.

**Comment by Metaxal** [comment]
I'll make a new quickscript repo/package with a new default directory for user-scripts in a `quickscript` subdirectory.

**Comment by Metaxal** [comment]
[Quickscript](https://github.com/Metaxal/quickscript) and [Quickscript extra](https://github.com/Metaxal/quickscript-extra)

The quickscript-library you made is a nice idea, but I'd rather have them in my own repo---that's easier to manage if everything is in one place. I'm also thinking that anyone should be able to write a package containing quickscript scripts and share it easily, just like a normal Racket package.

**Comment by Metaxal** [comment]
But don't use the new quickscript and quickscript-extra repo just yet---they're still work in progress.

You can still use the above method to try the new version.
