### ISSUE TITLE
Should the 'compile user scripts' menu item run 'reload scripts menu' by default?

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#23]
Should the 'compile user scripts' menu item run 'reload scripts menu' by default?

**Comment by Metaxal** [comment]
Maybe indeed. Or maybe the other way round, or both of them together all the time?

Please post your next issues in [quickscript](https://github.com/Metaxal/quickscript/issues), as this is going to be the next version (almost there, I just need to figure out how to properly deal with third-party scripts as packages). There are also some issues there waiting for you ;)

**Comment by Metaxal** [comment]
[follow up](https://github.com/Metaxal/quickscript/issues/2)
