### ISSUE TITLE
should this be tagged as 'deprecated' ?

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#24]
Is there a was to redirect script-plugin to quickscript on pkgd.racket-lang.org  ? (and GitHub)

PS you got a mention!
https://lang.video/blog/2018/03/21/making-an-ide-plugin-for-drracket/

**Comment by Metaxal** [comment]
Done. Thanks for the reminder! (I thought I had done it already, but apparently not.)

Cool for the mention, thanks Leif :)
