### ISSUE TITLE
this should be bundled with DrRacket.

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#4]
I'm going to propose it.

**Comment by spdegabrielle** [comment]
Raised as [https://github.com/racket/drracket/issues/168](https://github.com/racket/drracket/issues/168)

**Comment by Metaxal** [comment]
Thanks for proposing this :)

**Comment by Metaxal** [comment]
To be included in DrRacket, I think the script-plugin would need an overhaul.
I started a [wiki page](https://github.com/Metaxal/script-plugin/wiki/Possible-next-version) to list the principles and the possible changes that need to be done to have a chance to be included.

Feel free to add ideas.

**Comment by spdegabrielle** [comment]
I’ve added some comments.

**Comment by spdegabrielle** [comment]
Comments done.

I don't think a big overhaul is required - the only things I would do prior to a pull request to racket/racket would be give it a name & icon ('QuikScript' and a bright green lime(fruit) with fat tyres and chrome hot-rot exhaust pipes, eyes for lights and a smiling bumper bar)

A nice, but not necessary would be not importing all 'example' scripts into the users scripts directory by default. Choose some 'core' scripts, and leave the rest as optional to be imported with 'import bundled script...'

Stephen

**Comment by Metaxal** [comment]
Thanks for all the comments on the wiki, that's a good start!

**Comment by spdegabrielle** [comment]
Sorry I should be clear - I think script plugin is a well crafted piece of software and should be submitted ‘as is’.  

The wiki is clearly a version 2 or 3, and feedback from users will support that process.

**Comment by Metaxal** [comment]
:)
I think if we want to submit it to DrRacket, it's the right time to make backward-incompatible changes. I'll create a new branch and try a new version with one-file scripts.

**Comment by spdegabrielle** [comment]
Sounds awesome.

**Comment by Metaxal** [comment]
I have a local branch with one-file scripts. It works well, but I still need to port all the old scripts. Also I'm still unsure about how to deal with user scripts, bundled scripts, imported bundled scripts and updates. (Possibly, if the user imports a bundled scripts for editing, it cannot be updated anymore, unless reverted to 'bundled'?)

**Comment by spdegabrielle** [comment]
- I don't think it is unreasonable to expect the bundled scripts to overwrite old versions. 
- If a user slightly modifies a bundled script, leaving with the same filename, being overwritten by an upgrade would be expected.

**Comment by Metaxal** [comment]
Indeed, but some scripts may need to be tweaked by the user, e.g. the tweet script. In which case the user will not want to overwrite the script if there's a new version, but may still like to have the new functionalities of the new script (or s/he will be stuck with an outdated version)

Maybe that just means we should avoid scripts that need to be tweaked?

**Comment by spdegabrielle** [comment]
Avoiding Scripts need to be tweaked sounds like a good idea. Need a link to the library of scripts though.

**Comment by spdegabrielle** [comment]
Been thinking on this.

Is this a reasonable set of categories for scripts;
- default script - these come bundled, work out of the box, and you are unlikely to change  e.g.  colour
- script template - these come bundled with the intention that they are modified. e.g. 'author-...
- library script - script you might not include be default, but unlikely to be customised. e.g. ???
- library templates scripts - scripts that are intended to be customised e.g. 'tweet'

**Comment by spdegabrielle** [comment]
scratch that -too complex - maybe some later version 

I suggest creating a quickscripts-library repo on GitHub that can hold scripts for users to customise and add. (Istarted fiddling around with organisations on GitHub but I'm not sure that is the right thing)

**Comment by Metaxal** [comment]
Yes, that may be too complex. Ideally, there should be zero slope to start
using the plugin and be quickly operational.

**Comment by Metaxal** [comment]
Will be considered for [quickscript](https://github.com/Metaxal/quickscript) instead.
