### ISSUE TITLE
feedback/bug report causes DrRacket Internal Error

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#6]
feedback/bug report causes DrRacket Internal Error:
![image](https://user-images.githubusercontent.com/108047/33179620-fdcf1c8c-d061-11e7-8751-6a3d3e517eaa.png)

**Comment by Metaxal** [comment]
Thanks for the feedback! Indeed that dated back from the days of Planet. Should now be fixed (redirects to the github issue page)
