### ISSUE TITLE
'post definitions to PasteRack' script needed  

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#7]
Hi @stchang and @Metaxal,

A 'post definitions to [PasteRack](http://www.pasterack.org)' script is needed in the default scripts in [Script-Plugin](https://github.com/Metaxal/script-plugin)
It should 

1. Script 'POST's the contents of the currently active definitions window/tab to [PasteRack](http://www.pasterack.org)
3. User completes form in PasteRack 

I think PasteRack lacks an API for a post to fill in the form so I have logged an issue https://github.com/stchang/pasterack/issues/59

Kind regards, 

Stephen

**Comment by spdegabrielle** [comment]
an interim measure;
https://github.com/Metaxal/script-plugin/pull/10
@stchang @Metaxal

**Comment by spdegabrielle** [comment]
need to look at pr for https://github.com/stchang/pasterack to enable

**Comment by Metaxal** [comment]
closing since script-plugin is superseded by quickscript
