### ISSUE TITLE
Colour chooser script causes error

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/script-plugin#8]
Error in script file "color-chooser.rkt": Users/spdegabrielle/Library/Preferences/user-scripts/compiled/color-chooser_rkt.zo::1: read (compiled): wrong version for compiled code
  compiled version: 6.9.0.1
  expected version: 6.11

**Comment by Metaxal** [comment]
The error is not about the script itself, but a lack of recompilation of its file after you upgraded to Racket 6.11.
Normally for packages, running 'raco setup <package>' will recompile all the file, but in the present case these files are not directly part of the package but are copied into a different place, so raco setup will not work, I think (though you can still try, just in case).

A quick way to solve this is to simply delete the 'compiled' directory in 'Users/spdegabrielle/Library/Preferences/user-scripts/'. The next time any script is used, it will be recompiled automatically.

I'm looking for a way to do that more nicely for the user. Maybe add a "Recompile scripts" entry in "Manage scripts"?

**Comment by spdegabrielle** [comment]
> Maybe add a "Recompile scripts" entry in "Manage scripts"?

Sounds perfect, thanks
